/**
 * ChatWindow — Opened chat panel, positioned inside FloatingWidget's 60x60 anchor.
 *
 * Desktop / Tablet: position absolute, opens upward from the bubble anchor.
 * Mobile (<640px) : position fixed, fills visual viewport (adjusts on keyboard open).
 *
 * Backend integration points (marked with // TODO: BACKEND):
 *   - Each message is tagged with the parent conversationId
 *   - Ticket creation sends conversationId + phone data
 *   - Rating submission sends conversationId + rating
 *   - Chat close notifies backend to end the conversation
 *
 * Screen flow:
 *   chat --[X click]--------------► confirmModal (if messages exist)
 *   chat --[X click]--------------► onReturnToChat() (if empty)
 *     confirmModal --[Create Ticket]--► ticket-form screen
 *     confirmModal --[Close Chat]-----► rating screen
 *     confirmModal --[Return]---------► onReturnToChat() (hides, keeps msgs)
 *   ticket-form --[Submit]-----------► ticket-created screen
 *   ticket-created --[OK]------------► onClose() (clears + collapses)
 *   ticket-created --[Back]----------► chat
 *   rating --[Submit / Skip]---------► onClose() (clears + collapses)
 */

import { useState, useRef, useEffect } from 'react';
import { motion } from 'motion/react';
import { ChatHeader } from './ChatHeader';
import { ChatMessage } from './ChatMessage';
import { ChatInput } from './ChatInput';
import { ConfirmationModal } from './ConfirmationModal';
import { RatingScreen } from './RatingScreen';
import { EmptyState } from './EmptyState';
import { TypingIndicator } from './TypingIndicator';
import { TicketCreatedScreen } from './TicketCreatedScreen';
import { CreateTicketForm } from './CreateTicketForm';
import { ChatFooter } from './ChatFooter';
import { InactivityPrompt } from './InactivityPrompt';
import { downloadAsImage } from '../utils/downloadAsImage';
import {
  trackEvent, postMessage, postFeedback, postTicket, postRating, closeConversation,
} from '../utils/analytics';
import { sendMessage as sendBackendMessage, type ChatHistoryEntry } from '../utils/chatApi';
import type { Theme } from '../types/theme';
import type { MessageAttachment, Message } from './ChatWidget';
import type { ThemeSettings } from '../types/themeSettings';
import { DARK_MODE_COLORS, LIGHT_MODE_COLORS } from '../types/themeSettings';

type ScreenView = 'chat' | 'ticket-form' | 'ticket-created' | 'rating';

interface ChatWindowProps {
  theme: Theme;
  position: 'bottom-right' | 'bottom-left';
  /** Full close -- clears messages */
  onClose: () => void;
  /** Return to chat -- hides window, keeps messages */
  onReturnToChat: () => void;
  storeName: string;
  /** Store logo — wide banner shown in empty state (recommended 1024×256) */
  storeLogo?: string;
  /** Store icon — 32×32px avatar shown in header and next to agent messages */
  storeIcon?: string;
  /** Store identifier for backend calls */
  storeId: string;
  /** Unique conversation identifier (generated by FloatingWidget, confirmed by backend) */
  conversationId: string;
  /** Notify parent so it can persist the backend-issued conversation UUID */
  onConversationIdChange?: (id: string) => void;
  /** Lifted messages state from FloatingWidget */
  messages: Message[];
  setMessages: React.Dispatch<React.SetStateAction<Message[]>>;
  /** Theme settings for Light/Dark mode and custom colors */
  themeSettings?: ThemeSettings;
}

/**
 * Generate a temporary client-side ticket ID.
 * In production, the backend returns the real ticket ID via POST /tickets.
 */
function generateTicketId(): string {
  // TODO: BACKEND — Replace with backend-generated ticket ID
  return '#TKT-' + Math.floor(10000 + Math.random() * 90000);
}

function isShortAffirmative(text: string): boolean {
  const normalized = normalizeAssistantTriggerText(text);
  return /^(نعم|اي|اي نعم|إي|إي نعم|ايه|ايوه|أيوه|تمام|تم|اكيد|أكيد|yes|yeah|yep|ok|okay)$/.test(normalized);
}

function normalizeAssistantTriggerText(text?: string): string {
  return (text ?? '')
    .trim()
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u064B-\u065F\u0670]/g, '')
    .replace(/[إأآ]/g, 'ا')
    .replace(/ى/g, 'ي')
    .replace(/ة/g, 'ه')
    .replace(/[.!؟?،,؛:]/g, '')
    .replace(/\s+/g, ' ');
}

function isTicketOfferPrompt(text?: string): boolean {
  const normalized = normalizeAssistantTriggerText(text);
  return normalized.includes('يتواصل معك احد موظفي خدمه العملاء')
    || normalized.includes('اكلم خدمه العملاء')
    || (normalized.includes('customer service') && normalized.includes('contact'));
}

export function ChatWindow({
  theme, position, onClose, onReturnToChat,
  storeName, storeLogo, storeIcon, storeId, conversationId, onConversationIdChange,
  messages, setMessages,
  themeSettings,
}: ChatWindowProps) {
  const [isTyping, setIsTyping]               = useState(false);
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [currentScreen, setCurrentScreen]     = useState<ScreenView>('chat');
  const [ticketId, setTicketId]               = useState(generateTicketId);

  // ── Theme colors based on mode ──────────────────────────────────────────────
  const isDarkMode = themeSettings?.mode === 'dark';
  const modeColors = isDarkMode ? DARK_MODE_COLORS : LIGHT_MODE_COLORS;
  const mainColor = themeSettings?.mainColor || theme.background;

  /** Tracks how the current ticket was created: 'inline' or 'form' */
  const ticketSourceRef = useRef<'inline' | 'form'>('form');

  /** Whether a ticket has already been created for this conversation */
  const [ticketCreated, setTicketCreated] = useState(false);

  /** Guard ref to prevent double-trigger of ticket creation */
  const ticketCreatingRef = useRef(false);

  /** Ref for the entire chat widget container — used for native touch handlers */
  const widgetContainerRef = useRef<HTMLDivElement>(null);

  // ── Mobile keyboard / visual-viewport ────────────────────────────────────
  const [bottomOffset, setBottomOffset] = useState(0);
  const [isMobile, setIsMobile]         = useState(false);

  useEffect(() => {
    const check = () => setIsMobile(window.innerWidth < 640);
    check();
    window.addEventListener('resize', check);
    return () => window.removeEventListener('resize', check);
  }, []);

  useEffect(() => {
    if (!isMobile) { setBottomOffset(0); return; }
    const vv = window.visualViewport;
    if (!vv) return;
    const update = () => {
      setBottomOffset(Math.max(0, window.innerHeight - vv.height - vv.offsetTop));
    };
    vv.addEventListener('resize', update);
    vv.addEventListener('scroll', update);
    return () => {
      vv.removeEventListener('resize', update);
      vv.removeEventListener('scroll', update);
    };
  }, [isMobile]);

  // ── Auto-scroll ───────────────────────────────────────────────────────────
  const messagesContainerRef = useRef<HTMLDivElement>(null);
  const messagesEndRef       = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const c = messagesContainerRef.current;
    if (!c) return;
    c.scrollTop = c.scrollHeight;
    const raf = requestAnimationFrame(() => { c.scrollTop = c.scrollHeight; });
    const t   = setTimeout(() => {
      c.scrollTop = c.scrollHeight;
      messagesEndRef.current?.scrollIntoView({ block: 'end' });
    }, 150);
    return () => { cancelAnimationFrame(raf); clearTimeout(t); };
  }, [messages, isTyping, currentScreen]);

  const evCtx = { storeId, conversationId, ticketId: ticketCreated ? ticketId : undefined };

  const showInlineTicketForm = (trigger: string) => {
    if (messages.some(m => m.type === 'ticket-form' && !m.ticketFormSubmitted)) return;
    if (ticketCreated) {
      injectTicketAlreadyExistsMessage();
      return;
    }
    const ticketFormMsg: Message = {
      id: `ticket-form-${Date.now()}`,
      text: 'يرجى إدخال رقم هاتفك ليتم إنشاء تذكرة دعم لك:',
      sender: 'store',
      timestamp: new Date(),
      type: 'ticket-form',
      ticketFormSubmitted: false,
    };
    ticketSourceRef.current = 'inline';
    setMessages(prev => (
      prev.some(m => m.type === 'ticket-form' && !m.ticketFormSubmitted)
        ? prev
        : [...prev, ticketFormMsg]
    ));
    trackEvent('ticket.form_shown', evCtx, { source: 'inline', trigger });
  };

  // ── Message handlers ──────────────────────────────────────────────────────
  const handleSendMessage = async (text: string, attachment?: MessageAttachment) => {
    const lastAssistantMessage = [...messages].reverse().find(m => m.sender === 'store');
    const hasOpenTicketForm = messages.some(m => m.type === 'ticket-form' && !m.ticketFormSubmitted);
    const customerMsg: Message = {
      id: Date.now().toString(),
      text,
      sender: 'customer',
      attachment,
      timestamp: new Date(),
    };
    setMessages(prev => [...prev, customerMsg]);
    postMessage(evCtx, {
      messageId: customerMsg.id,
      sender: 'customer',
      text,
      attachment,
      timestamp: customerMsg.timestamp.toISOString(),
    });
    trackEvent('message.sent', evCtx, { hasAttachment: !!attachment });
    if (attachment) {
      trackEvent('attachment.uploaded', evCtx, {
        attachmentType: attachment.type, name: attachment.name, size: attachment.size,
      });
    }

    const lastAssistantOfferedTicket = lastAssistantMessage?.action === 'offer_ticket'
      || isTicketOfferPrompt(lastAssistantMessage?.text);

    if (!attachment && lastAssistantOfferedTicket && isShortAffirmative(text)) {
      showInlineTicketForm(hasOpenTicketForm ? 'affirmative_guard_duplicate' : 'affirmative_guard');
      return;
    }

    /* ── TEST TRIGGER: typing "A" shows inline ticket form ── */
    if (text.trim() === 'A') {
      setIsTyping(true);
      setTimeout(() => {
        setIsTyping(false);
        // If ticket already exists, show "already created" message instead of inline form
        if (ticketCreated) {
          const alreadyMsg: Message = {
            id: (Date.now() + 1).toString(),
            text: 'تم إنشاء تذكرة مسبقاً لهذه المحادثة.',
            sender: 'store',
            timestamp: new Date(),
            type: 'ticket-success',
          };
          setMessages(prev => [...prev, alreadyMsg]);
          return;
        }
        const ticketFormMsg: Message = {
          id: (Date.now() + 1).toString(),
          text: 'للمتابعة، يرجى إدخال رقم هاتفك حتى نتمكن من إنشاء تذكرة دعم لك:',
          sender: 'store',
          timestamp: new Date(),
          type: 'ticket-form',
          ticketFormSubmitted: false,
        };
        setMessages(prev => [...prev, ticketFormMsg]);
        ticketSourceRef.current = 'inline';
        trackEvent('ticket.form_shown', evCtx, { source: 'inline' });
      }, 900);
      return;
    }

    /* Real backend AI response */
    setIsTyping(true);
    const history: ChatHistoryEntry[] = messages.map(m => ({
      sender: m.sender === 'customer' ? 'customer' : 'store',
      text: m.text ?? '',
    }));
    const result = await sendBackendMessage(conversationId, text, history, attachment);
    setIsTyping(false);

    // Swap to backend-issued conversation UUID on first reply
    if (result.conversationId && result.conversationId !== conversationId) {
      onConversationIdChange?.(result.conversationId);
    }

    const replyText = result.reply
      || (result.rateLimited
        ? 'لقد تجاوزت الحد المسموح من الرسائل، حاول لاحقاً.'
        : result.error
          ? 'تعذّر الاتصال بالخادم، يرجى المحاولة مرة أخرى.'
          : 'شكراً لتواصلك معنا! سنقوم بالرد عليك قريباً.');
    // Detect a ticket-handoff offer from either the structured action OR a
    // text heuristic on the AI reply (n8n often returns next_action: "none").
    const isOfferTicket =
      result.action?.type === 'offer_ticket' || isTicketOfferPrompt(replyText);

    const response: Message = {
      id: result.aiMessageId || (Date.now() + 1).toString(),
      text: replyText,
      sender: 'store',
      timestamp: new Date(),
      action: isOfferTicket ? 'offer_ticket' : undefined,
    };

    if (isOfferTicket && !result.rateLimited && !result.error) {
      if (ticketCreated) {
        setMessages(prev => [...prev, response]);
        injectTicketAlreadyExistsMessage();
      } else {
        const ticketFormMsg: Message = {
          id: `${response.id}-form`,
          text: 'يرجى إدخال رقم هاتفك ليتم إنشاء تذكرة دعم لك:',
          sender: 'store',
          timestamp: new Date(),
          type: 'ticket-form',
          ticketFormSubmitted: false,
        };
        ticketSourceRef.current = 'inline';
        setMessages(prev => [...prev, response, ticketFormMsg]);
        trackEvent('ticket.form_shown', evCtx, { source: 'inline' });
      }
      postMessage(evCtx, {
        messageId: response.id,
        sender: 'store',
        text: response.text,
        timestamp: response.timestamp.toISOString(),
      });
      trackEvent('message.received', evCtx);
      return;
    }

    setMessages(prev => [...prev, response]);
    postMessage(evCtx, {
      messageId: response.id,
      sender: 'store',
      text: response.text,
      timestamp: response.timestamp.toISOString(),
    });
    trackEvent('message.received', evCtx);

    // Server-side close: chat-ai already marked the conversation closed
    // (AI farewell or user end_conversation). Advance to rating and emit
    // a telemetry-only event — do NOT re-send `conversation.closed` since
    // the DB row is already closed.
    if (result.intent === 'closed') {
      trackEvent('conversation.closed_by_ai', evCtx, { reason: result.action?.type ?? 'offer_close' });
      setTimeout(() => setCurrentScreen('rating'), 700);
    }
  };

  const handleQuickReplyPick = (messageId: string, value: 'yes' | 'no') => {
    setMessages(prev => prev.map(m => (m.id === messageId ? { ...m, quickReplyPicked: true } : m)));
    if (value === 'no') {
      closeConversation(evCtx, 'manual');
      setCurrentScreen('rating');
      return;
    }
    handleSendMessage('نعم');
  };

  /** Helper: injects a system message into chat indicating ticket already exists */
  const injectTicketAlreadyExistsMessage = () => {
    setMessages(prev => [
      ...prev,
      {
        id: `ticket-duplicate-${Date.now()}`,
        text: 'تم إنشاء تذكرة مسبقاً لهذه المحادثة.',
        sender: 'store' as const,
        timestamp: new Date(),
        type: 'ticket-success' as const,
      },
    ]);
  };

  /** Helper: append an error message inside the chat */
  const injectErrorMessage = (text: string) => {
    setMessages(prev => [
      ...prev,
      {
        id: `error-${Date.now()}`,
        text,
        sender: 'store' as const,
        timestamp: new Date(),
      },
    ]);
  };

  /* Inline ticket form submitted from inside a chat message */
  const handleInlineTicketSubmit = async (_phone: string, _dialCode: string) => {
    trackEvent('ticket.form_submitted', { ...evCtx, ticketId }, { source: 'inline' });
    if (ticketCreated) {
      injectTicketAlreadyExistsMessage();
      // Still mark the form as submitted so the UI doesn't show it again
      setMessages(prev =>
        prev.map(m =>
          m.type === 'ticket-form' && !m.ticketFormSubmitted
            ? { ...m, ticketFormSubmitted: true }
            : m,
        ),
      );
      return;
    }
    const res = await postTicket(
      { ...evCtx, ticketId },
      { subject: 'تذكرة من المحادثة', phone: `${_dialCode}${_phone.replace(/^0+/, '')}` },
    );
    if (!res?.ticketId) {
      injectErrorMessage('تعذّر إنشاء التذكرة، يرجى المحاولة مرة أخرى.');
      return;
    }
    setTicketCreated(true);
    if (res.displayCode) setTicketId(res.displayCode);
    setMessages(prev =>
      prev.map(m =>
        m.type === 'ticket-form' && !m.ticketFormSubmitted
          ? { ...m, ticketFormSubmitted: true }
          : m,
      ),
    );
    // Inject bot confirmation message inline, then auto-transition to rating.
    setTimeout(() => {
      setMessages(prev => [
        ...prev,
        {
          id: `ticket-confirm-${Date.now()}`,
          text: 'تم استلام رقمك ✅ سيتواصل معك أحد موظفي خدمة العملاء في أقرب وقت. شكراً لك 🌷',
          sender: 'store' as const,
          timestamp: new Date(),
        },
      ]);
    }, 400);
    setTimeout(() => {
      setCurrentScreen('rating');
    }, 5000);
  };

  // ── Download chat ─────────────────────────────────────────────────────────
  const handleDownload = () => {
    trackEvent('chat.exported', evCtx, { type: 'chat' });
    downloadAsImage({
      storeName,
      conversationId,
      ticketId: ticketCreated ? ticketId : undefined,
      messages,
      type: 'chat',
      isDarkMode,
    });
  };

  // ── Download ticket ───────────────────────────────────────────────────────
  const handleDownloadTicket = () => {
    trackEvent('chat.exported', { ...evCtx, ticketId }, { type: 'ticket' });
    downloadAsImage({
      storeName,
      conversationId,
      ticketId,
      messages,
      type: 'ticket',
      isDarkMode,
    });
  };

  // ── Screen flow handlers ──────────────────────────────────────────────────
  const handleCloseClick = () => {
    if (messages.length === 0) {
      onReturnToChat();
    } else {
      setShowConfirmModal(true);
    }
  };
  const handleConvertToTicket = () => {
    setShowConfirmModal(false);
    ticketSourceRef.current = 'form';
    ticketCreatingRef.current = false;
    setCurrentScreen('ticket-form');
    trackEvent('ticket.form_shown', evCtx, { source: 'form' });
  };
  const handleConfirmClose    = () => {
    setShowConfirmModal(false);
    closeConversation(evCtx, 'manual');
    setCurrentScreen('rating');
  };
  const handleReturnToChat    = () => { setShowConfirmModal(false); onReturnToChat(); };
  const handleTicketFormSubmit = async (_phone: string, _code: string) => {
    if (ticketCreatingRef.current || ticketCreated) return;
    ticketCreatingRef.current = true;
    trackEvent('ticket.form_submitted', { ...evCtx, ticketId }, { source: 'form' });
    const res = await postTicket(
      { ...evCtx, ticketId },
      { subject: 'تذكرة من المحادثة', phone: `${_code}${_phone.replace(/^0+/, '')}` },
    );
    if (!res?.ticketId) {
      ticketCreatingRef.current = false;
      injectErrorMessage('تعذّر إنشاء التذكرة، يرجى المحاولة مرة أخرى.');
      return;
    }
    setTicketCreated(true);
    if (res.displayCode) setTicketId(res.displayCode);
    setCurrentScreen('ticket-created');
  };
  const handleTicketFormBack   = () => { ticketCreatingRef.current = false; setCurrentScreen('chat'); };
  // Flow B — after ticket-created, send user to the rating screen so they
  // can rate the AI's handoff (not directly close the widget).
  // v4.7.22 — "حسناً، شكراً لك": end + full reset, then close. Next open = brand new chat.
  const handleTicketCreatedClose = () => {
    closeConversation(evCtx, 'user_ticket_acknowledged');
    onClose();
  };
  const handleTicketCreatedBack  = () => {
    // Only inject success message for the X → Create Ticket flow.
    // The inline flow already shows a green badge on the ticket-form message.
    if (ticketSourceRef.current === 'form') {
      setMessages(prev => {
        const lastMsg = prev[prev.length - 1];
        if (lastMsg?.type === 'ticket-success') return prev;
        return [
          ...prev,
          {
            id: `ticket-success-${Date.now()}`,
            text: 'تم إرسال طلبك بنجاح',
            sender: 'store' as const,
            timestamp: new Date(),
            type: 'ticket-success' as const,
          },
        ];
      });
    }
    setCurrentScreen('chat');
  };
  const handleRatingClose      = () => onClose();

  // ── Inactivity prompt (Continue / End) ────────────────────────────────────
  const inactivityEnabled = themeSettings?.inactivityEnabled !== false;
  const promptSeconds = Math.max(30, themeSettings?.inactivityPromptSeconds ?? 90);
  const closeSeconds  = Math.max(15, themeSettings?.inactivityCloseSeconds  ?? 60);
  const [showInactivityPrompt, setShowInactivityPrompt] = useState(false);
  const activityBumpRef = useRef(0);

  const bumpActivity = () => {
    activityBumpRef.current += 1;
    setShowInactivityPrompt(false);
  };

  useEffect(() => {
    bumpActivity();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [messages.length]);

  useEffect(() => {
    if (!inactivityEnabled) { setShowInactivityPrompt(false); return; }
    if (currentScreen !== 'chat' || messages.length === 0 || isTyping) return;

    const startBump = activityBumpRef.current;
    const showTimer = setTimeout(() => {
      if (activityBumpRef.current === startBump) {
        setShowInactivityPrompt(true);
        trackEvent('inactivity.prompt_shown', evCtx);
      }
    }, promptSeconds * 1000);
    return () => clearTimeout(showTimer);
  }, [inactivityEnabled, currentScreen, messages.length, isTyping, promptSeconds]);

  useEffect(() => {
    if (!showInactivityPrompt) return;
    const closeTimer = setTimeout(() => {
      setShowInactivityPrompt(false);
      closeConversation(evCtx, 'inactivity');
      setCurrentScreen('rating');
    }, closeSeconds * 1000);
    return () => clearTimeout(closeTimer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [showInactivityPrompt, closeSeconds]);

  const handleInactivityContinue = () => {
    trackEvent('inactivity.continued', evCtx);
    setShowInactivityPrompt(false);
    bumpActivity();
  };
  const handleInactivityEnd      = () => {
    trackEvent('inactivity.ended', evCtx);
    setShowInactivityPrompt(false);
    closeConversation(evCtx, 'inactivity');
    setCurrentScreen('rating');
  };

  // ── Backend auto-trigger ──────────────────────────────────────────────────
  useEffect(() => {
    const w = window as typeof window & { __chatWidget?: Record<string, () => void> };
    w.__chatWidget = {
      ...w.__chatWidget,
      triggerAutoTicket: () => showInlineTicketForm('manual_trigger'),
    };
  });

  // ── Positioning ──────────────────────────────────────────────────────────
  // NOTE: Body scroll lock is handled by FloatingWidget. No additional lock needed here.
  const windowStyle: React.CSSProperties = isMobile
    ? {
        position: 'fixed',
        top: '8px',
        left: '8px',
        right: '8px',
        bottom: `${bottomOffset + 8}px`,
        width: 'auto',
        height: 'auto',
        zIndex: 9999,
        transition: 'bottom 0.15s ease-out',
      }
    : {
        position: 'absolute',
        bottom: '0',
        ...(position === 'bottom-right' ? { right: 0 } : { left: 0 }),
        width: '400px',
        zIndex: 9999,
      };

  const transformOrigin =
    position === 'bottom-right' ? 'right bottom' : 'left bottom';

  return (
    <>
      <motion.div
        initial={{ opacity: 0, scale: 0.6 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.6 }}
        transition={{ type: 'spring', stiffness: 320, damping: 26 }}
        style={{
          transformOrigin,
          ...windowStyle,
          fontFamily: "'IBM Plex Sans Arabic', sans-serif",
          background: modeColors.chatBackground,
          borderColor: modeColors.chatBorder,
        }}
        className="rounded-3xl shadow-2xl flex flex-col overflow-hidden border"
        dir="rtl"
        onTouchMove={e => {
          // Prevent touch-scroll from leaking to body on non-scrollable areas
          const target = e.target as HTMLElement;
          const scrollable = target.closest('[data-chat-scrollable]');
          if (!scrollable) e.preventDefault();
        }}
        ref={widgetContainerRef}
      >
        <div
          className="flex flex-col overflow-hidden"
          style={{ height: isMobile ? '100%' : '580px' }}
        >
          {/* ── Rating ── */}
          {currentScreen === 'rating' && (
            <RatingScreen
              onClose={handleRatingClose}
              onBack={() => setCurrentScreen('chat')}
              storeName={storeName}
              theme={theme}
              isDarkMode={isDarkMode}
              mainColor={mainColor}
              // Disable rating-screen auto-close. The conversation is already
              // closed before this screen mounts, and customers complained
              // that the silent countdown was snapping the widget back.
              inactivitySeconds={0}
              onRatingSubmit={(stars, fb) => {
                const comment = typeof fb === 'string' ? fb.trim() : '';
                postRating(evCtx, { stars, comment: comment.length > 0 ? comment : undefined });
                closeConversation(evCtx, 'rating_submit');
              }}
              onRatingSkip={() => {
                postRating(evCtx, { stars: 0, skipped: true });
                trackEvent('rating.skipped', evCtx);
                closeConversation(evCtx, 'rating_skip');
              }}
              onRatingAutoClose={() => { /* disabled */ }}
            />
          )}

          {/* ── Ticket form (full-screen) ── */}
          {currentScreen === 'ticket-form' && (
            <CreateTicketForm
              theme={theme}
              storeName={storeName}
              onSubmit={handleTicketFormSubmit}
              onBack={handleTicketFormBack}
              ticketAlreadyCreated={ticketCreated}
              onDownload={handleDownloadTicket}
              isDarkMode={isDarkMode}
              mainColor={mainColor}
            />
          )}

          {/* ── Ticket created ── */}
          {currentScreen === 'ticket-created' && (
            <TicketCreatedScreen
              theme={theme}
              ticketId={ticketId}
              conversationId={conversationId}
              storeName={storeName}
              onClose={handleTicketCreatedClose}
              onBackToChat={handleTicketCreatedBack}
              onDownload={handleDownloadTicket}
              isDarkMode={isDarkMode}
              mainColor={mainColor}
            />
          )}

          {/* ── Main chat ── */}
          {currentScreen === 'chat' && (
            <>
              <ChatHeader
                storeName={storeName}
                storeIcon={storeIcon}
                onClose={handleCloseClick}
                onDownload={handleDownload}
                currentTheme={theme}
                mainColor={mainColor}
                isDarkMode={isDarkMode}
              />

              {/* Messages area */}
              <div
                ref={messagesContainerRef}
                data-chat-scrollable
                className="no-scrollbar flex-1 overflow-y-auto"
                style={{
                  background: modeColors.messagesBackground,
                  padding: '16px',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '12px',
                  overscrollBehavior: 'contain',
                  WebkitOverflowScrolling: 'touch',
                  touchAction: 'pan-y',
                }}
                onTouchMove={e => e.stopPropagation()}
              >
                {messages.length === 0 ? (
                  <EmptyState storeLogo={storeLogo} isDarkMode={isDarkMode} />
                ) : (
                  messages.map(message => (
                    <ChatMessage
                      key={message.id}
                      message={message}
                      storeIcon={storeIcon}
                      theme={theme}
                      onTicketFormSubmit={handleInlineTicketSubmit}
                      mainColor={mainColor}
                      isDarkMode={isDarkMode}
                      modeColors={modeColors}
                      onQuickReplyPick={handleQuickReplyPick}
                      onFeedbackChange={(id, fb) => {
                        setMessages(prev => prev.map(m => (m.id === id ? { ...m, feedback: fb } : m)));
                        postFeedback(evCtx, id, fb);
                        trackEvent('message.feedback', evCtx, { messageId: id, feedback: fb });
                      }}
                    />
                  ))
                )}
                {isTyping && <TypingIndicator storeIcon={storeIcon} theme={theme} mainColor={mainColor} isDarkMode={isDarkMode} />}
                {showInactivityPrompt && (
                  <InactivityPrompt
                    onContinue={handleInactivityContinue}
                    onEnd={handleInactivityEnd}
                    isDarkMode={isDarkMode}
                    mainColor={mainColor}
                  />
                )}
                <div ref={messagesEndRef} style={{ height: 1, flexShrink: 0 }} />
              </div>

              <ChatInput
                onSendMessage={handleSendMessage}
                isDisabled={isTyping}
                theme={theme}
                mainColor={mainColor}
                isDarkMode={isDarkMode}
                modeColors={modeColors}
              />
            </>
          )}

          {/* Branding footer — all screens */}
          <ChatFooter isDarkMode={isDarkMode} />
        </div>
      </motion.div>

      {/* Confirmation modal */}
      <ConfirmationModal
        isOpen={showConfirmModal}
        theme={theme}
        onClose={() => setShowConfirmModal(false)}
        onConfirmClose={handleConfirmClose}
        onConvertToTicket={handleConvertToTicket}
        onReturnToChat={handleReturnToChat}
        isDarkMode={isDarkMode}
        mainColor={mainColor}
      />
    </>
  );
}